version: '3'

services:
  # Database
  gorest_db:
    image: mysql:latest
    container_name: gorest_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: gorest
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - gorest-network

# Networks
networks:
  gorest-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local